import { VocabularyWord, Language } from './types';

export const SRS_INTERVALS_DAYS = [1, 3, 7, 16, 35, 80, 180]; // In days

export const TOTAL_QURAN_WORDS = 77430;

export const SUPPORTED_LANGUAGES: Language[] = [
    { code: 'en', name: 'English' },
    { code: 'ur', name: 'اردو (Urdu)' },
    { code: 'id', name: 'Bahasa Indonesia' },
    { code: 'fr', name: 'Français' },
    { code: 'bn', name: 'বাংলা (Bengali)' },
    { code: 'hi', name: 'हिन्दी (Hindi)' },
];

export const QURANIC_VOCABULARY: VocabularyWord[] = [
  {
    id: 1,
    arabic: 'مِن',
    transliteration: 'min',
    partOfSpeech: 'Particle',
    meanings: {
        en: 'From, of',
        ur: 'سے، کا',
        id: 'Dari, sebagian dari',
        fr: 'De, hors de',
        bn: 'থেকে, এর',
        hi: 'से, का',
    },
    exampleVerseArabic: 'مِنَ الْجِنَّةِ وَالنَّاسِ',
    exampleVerseTransliteration: 'mina al-jinnati wa-n-nās',
    exampleVerseTranslations: {
        en: 'From among the jinn and mankind.',
        ur: 'جنوں اور انسانوں میں سے۔',
        id: 'Dari (golongan) jin dan manusia.',
        fr: "Parmi les djinns et les hommes.",
        bn: 'জিন ও মানুষের মধ্য থেকে।',
        hi: 'जिन्न और मनुष्यों में से।',
    },
    verseReference: 'An-Nas 114:6',
    frequency: 3226,
    difficulty: 'Beginner',
  },
  {
    id: 3,
    arabic: 'اللَّهُ',
    transliteration: 'Allāh',
    partOfSpeech: 'Noun',
    meanings: {
        en: 'God',
        ur: 'اللہ',
        id: 'Tuhan',
        fr: 'Dieu',
        bn: 'আল্লাহ',
        hi: 'अल्लाह',
    },
    exampleVerseArabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ',
    exampleVerseTransliteration: 'Allāhu lā ilāha illā huwa al-ḥayyu al-qayyūm',
    exampleVerseTranslations: {
        en: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence.',
        ur: 'اللہ وہ ہے جس کے سوا کوئی معبود نہیں، وہ زندہ ہے، سب کا تھامنے والا ہے۔',
        id: 'Allah, tidak ada tuhan selain Dia. Yang Mahahidup, Yang terus-menerus mengurus (makhluk-Nya).',
        fr: "Allah! Point de divinité à part Lui, le Vivant, Celui qui subsiste par lui-même.",
        bn: 'আল্লাহ - তিনি ছাড়া আর কোনো উপাস্য নেই, তিনি চিরঞ্জীব, চিরস্থায়ী।',
        hi: 'अल्लाह - उसके सिवा कोई देवता नहीं है, वह सदा जीवित है, (सभी) अस्तित्व का निर्वाहक है।',
    },
    verseReference: 'Al-Baqarah 2:255',
    frequency: 2699,
    difficulty: 'Beginner',
  },
    {
    id: 4,
    arabic: 'أَنَّ',
    transliteration: 'anna',
    partOfSpeech: 'Particle',
    meanings: {
      en: 'That',
      ur: 'کہ',
      id: 'Bahwa',
      fr: 'Que',
      bn: 'যে',
      hi: 'कि',
    },
    exampleVerseArabic: 'ذَٰلِكَ بِأَنَّ اللَّهَ هُوَ الْحَقُّ',
    exampleVerseTransliteration: 'dhālika bi-anna Allāha huwa al-ḥaqq',
    exampleVerseTranslations: {
      en: 'That is because Allah is the Truth.',
      ur: 'یہ اس لیے کہ اللہ ہی حق ہے۔',
      id: 'Yang demikian itu karena sesungguhnya Allah, Dialah (Tuhan) Yang Haq.',
      fr: "C'est ainsi qu'Allah est la Vérité.",
      bn: 'এটা এই কারণে যে, আল্লাহই সত্য।',
      hi: 'यह इसलिए है क्योंकि अल्लाह ही सत्य है।',
    },
    verseReference: 'Al-Hajj 22:6',
    frequency: 1818,
    difficulty: 'Beginner',
  },
  {
    id: 2,
    arabic: 'فِي',
    transliteration: 'fī',
    partOfSpeech: 'Particle',
    meanings: {
      en: 'In, into',
      ur: 'میں',
      id: 'Di, di dalam',
      fr: 'Dans, en',
      bn: 'মধ্যে',
      hi: 'में',
    },
    exampleVerseArabic: 'فِي قُلُوبِهِم مَّرَضٌ',
    exampleVerseTransliteration: 'fī qulūbihim maraḍun',
    exampleVerseTranslations: {
      en: 'In their hearts is a disease.',
      ur: 'ان کے دلوں میں بیماری ہے۔',
      id: 'Dalam hati mereka ada penyakit.',
      fr: 'Il y a dans leurs cœurs une maladie.',
      bn: 'তাদের অন্তরে একটি রোগ আছে।',
      hi: 'उनके दिलों में एक बीमारी है।',
    },
    verseReference: 'Al-Baqarah 2:10',
    frequency: 1720,
    difficulty: 'Beginner',
  },
  {
    id: 10,
    arabic: 'لَا',
    transliteration: 'lā',
    partOfSpeech: 'Particle',
    meanings: {
      en: 'No, not',
      ur: 'نہیں',
      id: 'Tidak, jangan',
      fr: 'Non, ne... pas',
      bn: 'না',
      hi: 'नहीं',
    },
    exampleVerseArabic: 'لَا رَيْبَ ۛ فِيهِ',
    exampleVerseTransliteration: 'lā rayba fīh',
    exampleVerseTranslations: {
      en: 'There is no doubt in it.',
      ur: 'اس میں کوئی شک نہیں۔',
      id: 'Tidak ada keraguan padanya.',
      fr: "Il n'y a aucun doute là-dedans.",
      bn: 'এতে কোন সন্দেহ নেই।',
      hi: 'इसमें कोई संदेह नहीं है।',
    },
    verseReference: 'Al-Baqarah 2:2',
    frequency: 1690,
    difficulty: 'Beginner',
  },
    {
    id: 7,
    arabic: 'قَالَ',
    transliteration: 'qāla',
    partOfSpeech: 'Verb',
    meanings: {
      en: 'He said',
      ur: 'اس نے کہا',
      id: 'Dia berkata',
      fr: 'Il a dit',
      bn: 'তিনি বলেছেন',
      hi: 'उसने कहा',
    },
    exampleVerseArabic: 'قَالَ إِنِّي أَعْلَمُ مَا لَا تَعْلَمُونَ',
    exampleVerseTransliteration: 'qāla innī aʿlamu mā lā taʿlamūn',
    exampleVerseTranslations: {
      en: 'He said, "Indeed, I know that which you do not know."',
      ur: 'اس نے کہا، "میں وہ جانتا ہوں جو تم نہیں جانتے۔"',
      id: 'Dia berfirman, "Sungguh, Aku mengetahui apa yang tidak kamu ketahui."',
      fr: 'Il dit : "En vérité, Je sais ce que vous ne savez pas."',
      bn: 'তিনি বললেন, "আমি যা জানি তোমরা তা জানো না।"',
      hi: 'उसने कहा, "निश्चित रूप से, मैं वह जानता हूं जो तुम नहीं जानते।"',
    },
    verseReference: 'Al-Baqarah 2:30',
    frequency: 1618,
    difficulty: 'Beginner',
    root: 'ق-و-ل',
    etymology: "Derived from the triliteral root meaning 'to say', 'to speak', or 'to utter'. This is one of the most common verbs in the Quran.",
    derivatives: [
        { arabic: 'يَقُولُ', meaning: 'He says' },
        { arabic: 'قَوْل', meaning: 'A saying' },
        { arabic: 'قِيلَ', meaning: 'It was said' }
    ]
  },
  {
    id: 12,
    arabic: 'إِنَّ',
    transliteration: 'inna',
    partOfSpeech: 'Particle',
    meanings: {
      en: 'Indeed, truly',
      ur: 'بے شک، یقیناً',
      id: 'Sesungguhnya',
      fr: 'Certes, en vérité',
      bn: 'নিশ্চয়ই',
      hi: 'निश्चित रूप से, सचमुच',
    },
    exampleVerseArabic: 'إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    exampleVerseTransliteration: 'inna Allāha ʿalá kulli shayʾin qadīr',
    exampleVerseTranslations: {
      en: 'Indeed, Allah is over all things competent.',
      ur: 'بے شک اللہ ہر چیز پر قادر ہے۔',
      id: 'Sesungguhnya Allah Mahakuasa atas segala sesuatu.',
      fr: 'Certes, Allah est Omnipotent.',
      bn: 'নিশ্চয়ই আল্লাহ সব কিছুর উপর ক্ষমতাবান।',
      hi: 'निश्चित रूप से, अल्लाह हर चीज़ पर सक्षम है।',
    },
    verseReference: 'Al-Baqarah 2:20',
    frequency: 1600,
    difficulty: 'Beginner',
  },
  {
    id: 9,
    arabic: 'الَّذِي',
    transliteration: 'alladhī',
    partOfSpeech: 'Pronoun',
    meanings: {
      en: 'He who, which',
      ur: 'وہ جو',
      id: 'Yang',
      fr: 'Celui qui, qui',
      bn: 'যিনি',
      hi: 'वह जो',
    },
    exampleVerseArabic: 'الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا',
    exampleVerseTransliteration: 'alladhī jaʿala lakum al-arḍa firāshan',
    exampleVerseTranslations: {
      en: 'He who made for you the earth a bed.',
      ur: 'جس نے تمہارے لیے زمین کو بچھونا بنایا۔',
      id: 'Yang menjadikan bumi sebagai hamparan bagimu.',
      fr: 'Celui qui vous a fait la terre pour lit.',
      bn: 'যিনি তোমাদের জন্য পৃথিবীকে বিছানা বানিয়েছেন।',
      hi: 'जिसने तुम्हारे लिए पृथ्वी को बिस्तर बनाया।',
    },
    verseReference: 'Al-Baqarah 2:22',
    frequency: 1466,
    difficulty: 'Beginner',
  },
  {
    id: 6,
    arabic: 'عَلَى',
    transliteration: 'ʿalá',
    partOfSpeech: 'Particle',
    meanings: {
      en: 'On, upon, over',
      ur: 'پر',
      id: 'Di atas, atas',
      fr: 'Sur, au-dessus de',
      bn: 'উপরে',
      hi: 'पर, ऊपर',
    },
    exampleVerseArabic: 'وَعَلَى أَبْصَارِهِمْ غِشَاوَةٌ',
    exampleVerseTransliteration: 'wa-ʿalá abṣārihim ghishāwatun',
    exampleVerseTranslations: {
      en: 'And over their vision is a veil.',
      ur: 'اور ان کی آنکھوں پر پردہ ہے۔',
      id: 'Dan atas penglihatan mereka ada penutup.',
      fr: 'Et sur leurs yeux un voile.',
      bn: 'এবং তাদের দৃষ্টির উপর একটি পর্দা রয়েছে।',
      hi: 'और उनकी दृष्टि पर एक पर्दा है।',
    },
    verseReference: 'Al-Baqarah 2:7',
    frequency: 1425,
    difficulty: 'Beginner',
  },
  {
    id: 8,
    arabic: 'كَانَ',
    transliteration: 'kāna',
    partOfSpeech: 'Verb',
    meanings: {
      en: 'He was',
      ur: 'وہ تھا',
      id: 'Dia adalah',
      fr: 'Il était',
      bn: 'তিনি ছিলেন',
      hi: 'वह था',
    },
    exampleVerseArabic: 'وَكَانَ اللَّهُ عَلِيمًا حَكِيمًا',
    exampleVerseTransliteration: 'wa-kāna Allāhu ʿalīman ḥakīman',
    exampleVerseTranslations: {
      en: 'And ever is Allah Knowing and Wise.',
      ur: 'اور اللہ سب کچھ جاننے والا، حکمت والا ہے۔',
      id: 'Dan Allah Maha Mengetahui, Mahabijaksana.',
      fr: 'Et Allah est Omniscient et Sage.',
      bn: 'এবং আল্লাহ সর্বজ্ঞ, প্রজ্ঞাময়।',
      hi: 'और अल्लाह हमेशा से जानने वाला और बुद्धिमान है।',
    },
    verseReference: 'An-Nisa 4:17',
    frequency: 1358,
    difficulty: 'Beginner',
  },
  {
    id: 11,
    arabic: 'مَا',
    transliteration: 'mā',
    partOfSpeech: 'Particle/Pronoun',
    meanings: {
      en: 'What, not',
      ur: 'کیا، نہیں',
      id: 'Apa, tidak',
      fr: 'Que, ce que, ne...pas',
      bn: 'কি, না',
      hi: 'क्या, नहीं',
    },
    exampleVerseArabic: 'وَمَا هُم بِمُؤْمِنِينَ',
    exampleVerseTransliteration: 'wa-mā hum bi-muʾminīn',
    exampleVerseTranslations: {
      en: 'And they are not believers.',
      ur: 'اور وہ مومن نہیں ہیں۔',
      id: 'Dan mereka itu bukanlah orang-orang yang beriman.',
      fr: 'Et ils ne sont pas croyants.',
      bn: 'এবং তারা বিশ্বাসী নয়।',
      hi: 'और वे विश्वासी नहीं हैं।',
    },
    verseReference: 'Al-Baqarah 2:8',
    frequency: 1184,
    difficulty: 'Beginner',
  },
  {
    id: 14,
    arabic: 'رَبّ',
    transliteration: 'rabb',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Lord',
      ur: 'رب',
      id: 'Tuhan',
      fr: 'Seigneur',
      bn: 'প্রভু',
      hi: 'भगवान',
    },
    exampleVerseArabic: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
    exampleVerseTransliteration: 'al-ḥamdu lillāhi rabbi al-ʿālamīn',
    exampleVerseTranslations: {
      en: 'All praise is for Allah, Lord of the worlds.',
      ur: 'تمام تعریفیں اللہ کے لیے ہیں جو تمام جہانوں کا رب ہے۔',
      id: 'Segala puji bagi Allah, Tuhan seluruh alam.',
      fr: 'Louange à Allah, Seigneur de l univers.',
      bn: 'সমস্ত প্রশংসা আল্লাহর জন্য, যিনি জগতসমূহের প্রতিপালক।',
      hi: 'सारी प्रशंसा अल्लाह के लिए है, जो सारे संसार का भगवान है।',
    },
    verseReference: 'Al-Fatihah 1:2',
    frequency: 973,
    difficulty: 'Beginner',
  },
  {
    id: 5,
    arabic: 'إِلَى',
    transliteration: 'ilá',
    partOfSpeech: 'Particle',
    meanings: {
      en: 'To, towards',
      ur: 'کی طرف',
      id: 'Ke, kepada',
      fr: 'Vers, à',
      bn: 'দিকে',
      hi: 'की ओर',
    },
    exampleVerseArabic: 'ثُمَّ أَتِمُّوا الصِّيَامَ إِلَى اللَّيْلِ',
    exampleVerseTransliteration: 'thumma atimmū aṣ-ṣiyāma ilá al-layl',
    exampleVerseTranslations: {
      en: 'Then complete the fast until the night.',
      ur: 'پھر رات تک روزہ پورا کرو۔',
      id: 'Kemudian sempurnakanlah puasa sampai (datang) malam.',
      fr: 'Puis complétez le jeûne jusquà la nuit.',
      bn: 'তারপর রাত পর্যন্ত রোজা পূর্ণ কর।',
      hi: 'फिर रात तक रोज़ा पूरा करो।',
    },
    verseReference: 'Al-Baqarah 2:187',
    frequency: 737,
    difficulty: 'Beginner',
  },
    {
    id: 15,
    arabic: 'بِ',
    transliteration: 'bi',
    partOfSpeech: 'Particle',
    meanings: {
      en: 'With, in',
      ur: 'ساتھ، میں',
      id: 'Dengan, di dalam',
      fr: 'Avec, en',
      bn: 'সঙ্গে, মধ্যে',
      hi: 'साथ, में',
    },
    exampleVerseArabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
    exampleVerseTransliteration: 'bismi Allāhi ar-raḥmāni ar-raḥīm',
    exampleVerseTranslations: {
      en: 'In the name of Allah, the Entirely Merciful, the Especially Merciful.',
      ur: 'اللہ کے نام سے جو بڑا مہربان، نہایت رحم والا ہے۔',
      id: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang.',
      fr: 'Au nom d Allah, le Tout Miséricordieux, le Très Miséricordieux.',
      bn: 'আল্লাহর নামে, যিনি পরম করুণাময়, অতি দয়ালু।',
      hi: 'अल्लाह के नाम से, जो अत्यंत दयालु, विशेष रूप से दयालु है।',
    },
    verseReference: 'Al-Fatihah 1:1',
    frequency: 569,
    difficulty: 'Beginner',
  },
  {
    id: 17,
    arabic: 'كُفْر',
    transliteration: 'kufr',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Disbelief, denial',
      ur: 'کفر، انکار',
      id: 'Kekafiran, penolakan',
      fr: 'Mécréance, déni',
      bn: 'অবিশ্বাস, অস্বীকার',
      hi: 'अविश्वास, इनकार',
    },
    exampleVerseArabic: 'وَمَن يَكْفُرْ بِالْإِيمَانِ فَقَدْ حَبِطَ عَمَلُهُ',
    exampleVerseTransliteration: 'wa-man yakfur bi-l-īmāni faqad ḥabiṭa ʿamaluh',
    exampleVerseTranslations: {
      en: 'And whoever denies the faith - his work has become worthless.',
      ur: 'اور جو کوئی ایمان کا انکار کرے تو اس کا عمل ضائع ہوگیا۔',
      id: 'Barangsiapa kafir setelah beriman, maka sungguh, sia-sia amal mereka.',
      fr: 'Et quiconque renie la foi, alors vaines seront ses œuvres.',
      bn: 'আর যে ঈমানকে অস্বীকার করবে, তার কাজ নিষ্ফল হয়ে যাবে।',
      hi: 'और जो कोई ईमान से इनकार करता है - उसका काम व्यर्थ हो गया है।',
    },
    verseReference: 'Al-Maidah 5:5',
    frequency: 525,
    difficulty: 'Beginner',
    root: 'ك-ف-ر',
    etymology: "From the root meaning 'to cover' or 'to conceal'. In a theological context, it refers to concealing the truth or showing ingratitude to God's blessings.",
  },
  {
    id: 43,
    arabic: 'شَيْء',
    transliteration: 'shayʾ',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Thing',
      ur: 'چیز',
      id: 'Sesuatu',
      fr: 'Chose',
      bn: 'জিনিস',
      hi: 'चीज़',
    },
    exampleVerseArabic: 'إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    exampleVerseTransliteration: 'inna Allāha ʿalá kulli shayʾin qadīr',
    exampleVerseTranslations: {
      en: 'Indeed, Allah is over all things competent.',
      ur: 'بے شک اللہ ہر چیز پر قادر ہے۔',
      id: 'Sesungguhnya Allah Mahakuasa atas segala sesuatu.',
      fr: 'Certes, Allah est Omnipotent.',
      bn: 'নিশ্চয়ই আল্লাহ সব কিছুর উপর ক্ষমতাবান।',
      hi: 'निश्चित रूप से, अल्लाह हर चीज़ पर सक्षम है।',
    },
    verseReference: 'Al-Baqarah 2:20',
    frequency: 519,
    difficulty: 'Beginner',
  },
  {
    id: 13,
    arabic: 'هُوَ',
    transliteration: 'huwa',
    partOfSpeech: 'Pronoun',
    meanings: {
      en: 'He, it',
      ur: 'وہ',
      id: 'Dia',
      fr: 'Il, lui',
      bn: 'তিনি',
      hi: 'वह',
    },
    exampleVerseArabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ',
    exampleVerseTransliteration: 'qul huwa Allāhu aḥad',
    exampleVerseTranslations: {
      en: 'Say, "He is Allah, [who is] One."',
      ur: 'کہو، "وہ اللہ ایک ہے۔"',
      id: 'Katakanlah, "Dialah Allah, Yang Maha Esa."',
      fr: 'Dis: "Il est Allah, Unique."',
      bn: 'বলুন, "তিনি আল্লাহ, এক ও অদ্বিতীয়।"',
      hi: 'कहो, "वह अल्लाह है, जो एक है।"',
    },
    verseReference: 'Al-Ikhlas 112:1',
    frequency: 483,
    difficulty: 'Intermediate',
  },
  {
    id: 21,
    arabic: 'يَوْم',
    transliteration: 'yawm',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Day',
      ur: 'دن',
      id: 'Hari',
      fr: 'Jour',
      bn: 'দিন',
      hi: 'दिन',
    },
    exampleVerseArabic: 'مَالِكِ يَوْمِ الدِّينِ',
    exampleVerseTransliteration: 'māliki yawmi ad-dīn',
    exampleVerseTranslations: {
      en: 'Sovereign of the Day of Recompense.',
      ur: 'جزا کے دن کا مالک۔',
      id: 'Pemilik hari pembalasan.',
      fr: 'Maître du Jour de la Rétribution.',
      bn: 'প্রতিফল দিবসের মালিক।',
      hi: 'प्रतिफल के दिन का स्वामी।',
    },
    verseReference: 'Al-Fatihah 1:4',
    frequency: 475,
    difficulty: 'Intermediate',
  },
  {
    id: 22,
    arabic: 'أَرْض',
    transliteration: 'arḍ',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Earth',
      ur: 'زمین',
      id: 'Bumi',
      fr: 'Terre',
      bn: 'পৃথিবী',
      hi: 'पृथ्वी',
    },
    exampleVerseArabic: 'وَإِلَى الْأَرْضِ كَيْفَ سُطِحَتْ',
    exampleVerseTransliteration: 'wa-ilá al-arḍi kayfa suṭiḥat',
    exampleVerseTranslations: {
      en: 'And at the earth - how it is spread out?',
      ur: 'اور زمین کی طرف کہ وہ کیسے بچھائی گئی؟',
      id: 'Dan bumi bagaimana ia dihamparkan?',
      fr: 'Et la terre comment elle est nivelée?',
      bn: 'এবং পৃথিবীর দিকে, কিভাবে তা বিছানো হয়েছে?',
      hi: 'और पृथ्वी की ओर - यह कैसे फैली हुई है?',
    },
    verseReference: 'Al-Ghashiyah 88:20',
    frequency: 461,
    difficulty: 'Intermediate',
  },
  {
    id: 25,
    arabic: 'آيَة',
    transliteration: 'āyah',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Sign, verse',
      ur: 'نشانی، آیت',
      id: 'Tanda, ayat',
      fr: 'Signe, verset',
      bn: 'নিদর্শন, আয়াত',
      hi: 'चिन्ह, आयत',
    },
    exampleVerseArabic: 'وَجَعَلْنَا ابْنَ مَرْيَمَ وَأُمَّهُ آيَةً',
    exampleVerseTransliteration: 'wa-jaʿalnā ibna Maryama wa-ummahū āyah',
    exampleVerseTranslations: {
      en: 'And We made the son of Mary and his mother a sign.',
      ur: 'اور ہم نے مریم کے بیٹے اور اس کی ماں کو ایک نشانی بنایا۔',
      id: 'Dan Kami jadikan putra Maryam beserta ibunya sebagai suatu bukti.',
      fr: 'Et Nous fîmes du fils de Marie, ainsi que de sa mère, un signe.',
      bn: 'এবং আমি মরিয়মের পুত্র ও তার মাকে একটি নিদর্শন বানিয়েছিলাম।',
      hi: 'और हमने मरियम के बेटे और उसकी माँ को एक निशानी बनाया।',
    },
    verseReference: 'Al-Mu’minun 23:50',
    frequency: 382,
    difficulty: 'Intermediate',
  },
  {
    id: 35,
    arabic: 'عَمَل',
    transliteration: 'ʿamal',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Deed, work',
      ur: 'عمل، کام',
      id: 'Amal, perbuatan',
      fr: 'Œuvre, action',
      bn: 'কাজ, আমল',
      hi: 'कर्म, कार्य',
    },
    exampleVerseArabic: 'إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ',
    exampleVerseTransliteration: 'inna alladhīna āmanū wa-ʿamilū aṣ-ṣāliḥāt',
    exampleVerseTranslations: {
      en: 'Indeed, they who have believed and done righteous deeds.',
      ur: 'بے شک جو لوگ ایمان لائے اور انہوں نے نیک عمل کئے۔',
      id: 'Sesungguhnya orang-orang yang beriman dan mengerjakan kebajikan.',
      fr: 'Certes, ceux qui croient et accomplissent les bonnes œuvres.',
      bn: 'নিশ্চয়ই যারা ঈমান এনেছে এবং সৎকাজ করেছে।',
      hi: 'निश्चित रूप से, वे जो ईमान लाए और अच्छे कर्म किए।',
    },
    verseReference: 'Al-Baqarah 2:277',
    frequency: 360,
    difficulty: 'Intermediate',
    root: 'ع-م-ل',
    etymology: "From the root meaning 'to do', 'to act', or 'to work'. It encompasses any action or deed, often used in the context of righteous works.",
  },
  {
    id: 18,
    arabic: 'رَسُول',
    transliteration: 'rasūl',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Messenger',
      ur: 'رسول',
      id: 'Rasul',
      fr: 'Messager',
      bn: 'রসূল',
      hi: 'दूत',
    },
    exampleVerseArabic: 'مُّحَمَّدٌ رَّسُولُ اللَّهِ',
    exampleVerseTransliteration: 'Muḥammadun rasūlu Allāh',
    exampleVerseTranslations: {
      en: 'Muhammad is the Messenger of Allah.',
      ur: 'محمد اللہ کے رسول ہیں۔',
      id: 'Muhammad adalah utusan Allah.',
      fr: 'Muhammad est le Messager d Allah.',
      bn: 'মুহাম্মদ আল্লাহর রসূল।',
      hi: 'मुहम्मद अल्लाह के दूत हैं।',
    },
    verseReference: 'Al-Fath 48:29',
    frequency: 332,
    difficulty: 'Intermediate',
  },
  {
    id: 23,
    arabic: 'سَمَاء',
    transliteration: 'samāʾ',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Sky, heaven',
      ur: 'آسمان',
      id: 'Langit',
      fr: 'Ciel',
      bn: 'আকাশ',
      hi: 'आकाश',
    },
    exampleVerseArabic: 'الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً',
    exampleVerseTransliteration: 'alladhī jaʿala lakum al-arḍa firāshan wa-s-samāʾa bināʾā',
    exampleVerseTranslations: {
      en: '[He] who made for you the earth a bed and the sky a ceiling.',
      ur: 'جس نے تمہارے لیے زمین کو بچھونا اور آسمان کو چھت بنایا۔',
      id: 'Yang menjadikan bumi sebagai hamparan bagimu dan langit sebagai atap.',
      fr: 'Celui qui vous a fait la terre pour lit et le ciel pour toit.',
      bn: 'যিনি তোমাদের জন্য পৃথিবীকে বিছানা এবং আকাশকে ছাদ বানিয়েছেন।',
      hi: 'जिसने तुम्हारे लिए पृथ्वी को बिस्तर और आकाश को छत बनाया।',
    },
    verseReference: 'Al-Baqarah 2:22',
    frequency: 310,
    difficulty: 'Intermediate',
  },
  {
    id: 42,
    arabic: 'نَفْس',
    transliteration: 'nafs',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Soul, self',
      ur: 'جان، نفس',
      id: 'Jiwa, diri',
      fr: 'Âme, personne',
      bn: 'আত্মা, প্রাণ',
      hi: 'आत्मा, स्वयं',
    },
    exampleVerseArabic: 'كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ',
    exampleVerseTransliteration: 'kullu nafsin dhāʾiqatu al-mawt',
    exampleVerseTranslations: {
      en: 'Every soul will taste death.',
      ur: 'ہر جان موت کا ذائقہ چکھنے والی ہے۔',
      id: 'Setiap yang berjiwa akan merasakan mati.',
      fr: 'Chaque âme goûtera la mort.',
      bn: 'প্রত্যেক আত্মাকে মৃত্যুর স্বাদ গ্রহণ করতে হবে।',
      hi: 'हर आत्मा मृत्यु का स्वाद चखेगी।',
    },
    verseReference: 'Aal-E-Imran 3:185',
    frequency: 298,
    difficulty: 'Intermediate',
  },
  {
    id: 26,
    arabic: 'حَقّ',
    transliteration: 'ḥaqq',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Truth, right',
      ur: 'حق، سچ',
      id: 'Kebenaran, hak',
      fr: 'Vérité, droit',
      bn: 'সত্য, অধিকার',
      hi: 'सत्य, अधिकार',
    },
    exampleVerseArabic: 'وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ',
    exampleVerseTransliteration: 'wa-lā talbisū al-ḥaqqa bi-l-bāṭil',
    exampleVerseTranslations: {
      en: 'And do not mix the truth with falsehood.',
      ur: 'اور حق کو باطل کے ساتھ نہ ملاؤ۔',
      id: 'Dan janganlah kamu campuradukkan kebenaran dengan kebatilan.',
      fr: 'Et ne mêlez pas le faux à la vérité.',
      bn: 'এবং সত্যকে মিথ্যার সাথে মিশ্রিত করো না।',
      hi: 'और सत्य को असत्य के साथ न मिलाओ।',
    },
    verseReference: 'Al-Baqarah 2:42',
    frequency: 287,
    difficulty: 'Intermediate',
  },
  {
    id: 19,
    arabic: 'كِتَاب',
    transliteration: 'kitāb',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Book, scripture',
      ur: 'کتاب',
      id: 'Buku, kitab',
      fr: 'Livre, Écriture',
      bn: 'বই, গ্রন্থ',
      hi: 'किताब, शास्त्र',
    },
    exampleVerseArabic: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ',
    exampleVerseTransliteration: 'dhālika al-kitābu lā rayba fīh',
    exampleVerseTranslations: {
      en: 'This is the Book about which there is no doubt.',
      ur: 'یہ وہ کتاب ہے جس میں کوئی شک نہیں۔',
      id: 'Kitab ini tidak ada keraguan padanya.',
      fr: 'Voici le Livre au sujet duquel il n y a aucun doute.',
      bn: 'এই সেই কিতাব যাতে কোন সন্দেহ নেই।',
      hi: 'यह वह किताब है जिसके बारे में कोई संदेह नहीं है।',
    },
    verseReference: 'Al-Baqarah 2:2',
    frequency: 261,
    difficulty: 'Intermediate',
    root: 'ك-ت-ب',
    etymology: "Derived from the root meaning 'to write'. It refers to anything written, most notably a scripture or a divine book.",
    derivatives: [
        { arabic: 'يَكْتُبُ', meaning: 'He writes' },
        { arabic: 'مَكْتُوب', meaning: 'Written' }
    ]
  },
  {
    id: 16,
    arabic: 'إِيمَان',
    transliteration: 'īmān',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Faith, belief',
      ur: 'ایمان، یقین',
      id: 'Iman, keyakinan',
      fr: 'Foi, croyance',
      bn: 'ঈমান, বিশ্বাস',
      hi: 'ईमान, विश्वास',
    },
    exampleVerseArabic: 'الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللَّهِ',
    exampleVerseTransliteration: 'alladhīna āmanū wa-taṭmaʾinnu qulūbuhum bi-dhikri Allāh',
    exampleVerseTranslations: {
      en: 'Those who have believed and whose hearts are assured by the remembrance of Allah.',
      ur: 'جو لوگ ایمان لائے اور ان کے دل اللہ کی یاد سے اطمینان پاتے ہیں۔',
      id: 'Orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah.',
      fr: 'Ceux qui ont cru, et dont les cœurs se tranquillisent à l évocation d Allah.',
      bn: 'যারা ঈমান এনেছে এবং আল্লাহর স্মরণে যাদের অন্তর প্রশান্ত হয়।',
      hi: 'वे जो ईमान लाए और जिनके दिल अल्लाह की याद से आश्वस्त होते हैं।',
    },
    verseReference: 'Ar-Ra`d 13:28',
    frequency: 247,
    difficulty: 'Intermediate',
  },
  {
    id: 24,
    arabic: 'نَاس',
    transliteration: 'nās',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'People, mankind',
      ur: 'لوگ، انسان',
      id: 'Manusia',
      fr: 'Gens, humanité',
      bn: 'মানুষ, মানবজাতি',
      hi: 'लोग, मानवजाति',
    },
    exampleVerseArabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
    exampleVerseTransliteration: 'qul aʿūdhu bi-rabbi an-nās',
    exampleVerseTranslations: {
      en: 'Say, "I seek refuge in the Lord of mankind."',
      ur: 'کہو، "میں انسانوں کے رب کی پناہ مانگتا ہوں۔"',
      id: 'Katakanlah, "Aku berlindung kepada Tuhannya manusia."',
      fr: 'Dis: "Je cherche refuge auprès du Seigneur des hommes."',
      bn: 'বলুন, "আমি আশ্রয় প্রার্থনা করছি মানুষের প্রতিপালকের কাছে।"',
      hi: 'कहो, "मैं मानवजाति के भगवान की शरण लेता हूं।"',
    },
    verseReference: 'An-Nas 114:1',
    frequency: 241,
    difficulty: 'Intermediate',
  },
  {
    id: 40,
    arabic: 'حَيَاة',
    transliteration: 'ḥayāh',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Life',
      ur: 'زندگی',
      id: 'Kehidupan',
      fr: 'Vie',
      bn: 'জীবন',
      hi: 'जीवन',
    },
    exampleVerseArabic: 'وَمَا هَٰذِهِ الْحَيَاةُ الدُّنْيَا إِلَّا لَهْوٌ وَلَعِبٌ',
    exampleVerseTransliteration: 'wa-mā hādhihi al-ḥayātu ad-dunyā illā lahwun wa-laʿib',
    exampleVerseTranslations: {
      en: 'And this worldly life is not but diversion and amusement.',
      ur: 'اور یہ دنیا کی زندگی تو صرف کھیل اور تماشا ہے۔',
      id: 'Dan kehidupan dunia ini tidak lain hanyalah senda gurau dan permainan.',
      fr: 'Cette vie d ici-bas n est qu amusement et jeu.',
      bn: 'এবং এই দুনিয়ার জীবন খেলাধুলা ও বিনোদন ছাড়া আর কিছুই নয়।',
      hi: 'और यह सांसारिक जीवन मनोरंजन और खेल के अलावा कुछ नहीं है।',
    },
    verseReference: 'Al-Ankabut 29:64',
    frequency: 184,
    difficulty: 'Intermediate',
  },
  {
    id: 31,
    arabic: 'جَنَّة',
    transliteration: 'jannah',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Garden, paradise',
      ur: 'باغ، جنت',
      id: 'Taman, surga',
      fr: 'Jardin, paradis',
      bn: 'বাগান, জান্নাত',
      hi: 'बाग, स्वर्ग',
    },
    exampleVerseArabic: 'وَبَشِّرِ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ',
    exampleVerseTransliteration: 'wa-bashshiri alladhīna āmanū wa-ʿamilū aṣ-ṣāliḥāti anna lahum jannāt',
    exampleVerseTranslations: {
      en: 'And give good tidings to those who believe and do righteous deeds that they will have gardens.',
      ur: 'اور جو لوگ ایمان لائے اور نیک عمل کیے انہیں خوشخبری دو کہ ان کے لیے باغات ہیں۔',
      id: 'Dan sampaikanlah kabar gembira kepada orang-orang yang beriman dan berbuat kebajikan, bahwa untuk mereka (disediakan) surga-surga.',
      fr: 'Annonce à ceux qui croient et pratiquent de bonnes œuvres qu ils auront pour demeures des jardins.',
      bn: 'এবং যারা ঈমান এনেছে এবং সৎকর্ম করেছে তাদেরকে সুসংবাদ দাও যে, তাদের জন্য বাগান রয়েছে।',
      hi: 'और जो लोग ईमान लाए और अच्छे कर्म किए, उन्हें खुशखबरी दो कि उनके लिए बाग होंगे।',
    },
    verseReference: 'Al-Baqarah 2:25',
    frequency: 147,
    difficulty: 'Intermediate',
  },
  {
    id: 32,
    arabic: 'نَار',
    transliteration: 'nār',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Fire, hell',
      ur: 'آگ، جہنم',
      id: 'Api, neraka',
      fr: 'Feu, enfer',
      bn: 'আগুন, জাহান্নাম',
      hi: 'आग, नरक',
    },
    exampleVerseArabic: 'فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ',
    exampleVerseTransliteration: 'fa-ttaqū an-nāra allatī waqūduhā an-nāsu wa-l-ḥijārah',
    exampleVerseTranslations: {
      en: 'Then fear the Fire, whose fuel is men and stones.',
      ur: 'تو اس آگ سے بچو جس کا ایندھن انسان اور پتھر ہیں۔',
      id: 'Maka takutlah kamu akan api neraka yang bahan bakarnya adalah manusia dan batu.',
      fr: 'Craignez le Feu dont le combustible sera les hommes et les pierres.',
      bn: 'অতএব সেই আগুনকে ভয় কর যার ইন্ধন হবে মানুষ ও পাথর।',
      hi: 'तो उस आग से डरो, जिसका ईंधन आदमी और पत्थर हैं।',
    },
    verseReference: 'Al-Baqarah 2:24',
    frequency: 145,
    difficulty: 'Intermediate',
  },
  {
    id: 27,
    arabic: 'نَبِيّ',
    transliteration: 'nabīy',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Prophet',
      ur: 'نبی',
      id: 'Nabi',
      fr: 'Prophète',
      bn: 'নবী',
      hi: 'नबी',
    },
    exampleVerseArabic: 'يَا أَيُّهَا النَّبِيُّ حَسْبُكَ اللَّهُ',
    exampleVerseTransliteration: 'yā ayyuhā an-nabīyyu ḥasbuka Allāh',
    exampleVerseTranslations: {
      en: 'O Prophet, sufficient for you is Allah.',
      ur: 'اے نبی، آپ کے لیے اللہ کافی ہے۔',
      id: 'Wahai Nabi, cukuplah Allah (menjadi pelindung) bagimu.',
      fr: 'Ô Prophète, Allah te suffit.',
      bn: 'হে নবী, আপনার জন্য আল্লাহই যথেষ্ট।',
      hi: 'हे नबी, आपके लिए अल्लाह ही काफी है।',
    },
    verseReference: 'Al-Anfal 8:64',
    frequency: 144,
    difficulty: 'Intermediate',
  },
  {
    id: 33,
    arabic: 'قَلْب',
    transliteration: 'qalb',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Heart',
      ur: 'دل',
      id: 'Hati',
      fr: 'Cœur',
      bn: 'অন্তর, হৃদয়',
      hi: 'दिल, हृदय',
    },
    exampleVerseArabic: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    exampleVerseTransliteration: 'alā bi-dhikri Allāhi taṭmaʾinnu al-qulūb',
    exampleVerseTranslations: {
      en: 'Unquestionably, by the remembrance of Allah hearts are assured.',
      ur: 'خبردار! اللہ کی یاد سے ہی دلوں کو اطمینان ملتا ہے۔',
      id: 'Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.',
      fr: 'N est-ce pas par l évocation d Allah que les cœurs se tranquillisent?',
      bn: 'জেনে রেখো, আল্লাহর স্মরণেই অন্তর প্রশান্ত হয়।',
      hi: 'निश्चित रूप से, अल्लाह की याद से दिलों को सुकून मिलता है।',
    },
    verseReference: 'Ar-Ra`d 13:28',
    frequency: 132,
    difficulty: 'Intermediate',
  },
  {
    id: 38,
    arabic: 'أَهْل',
    transliteration: 'ahl',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Family, people',
      ur: 'گھر والے، لوگ',
      id: 'Keluarga, penduduk',
      fr: 'Famille, gens',
      bn: 'পরিবার, লোক',
      hi: 'परिवार, लोग',
    },
    exampleVerseArabic: 'قُوا أَنفُسَكُمْ وَأَهْلِيكُمْ نَارًا',
    exampleVerseTransliteration: 'qū anfusakum wa-ahlīkum nārā',
    exampleVerseTranslations: {
      en: 'Protect yourselves and your families from a Fire.',
      ur: 'اپنے آپ کو اور اپنے گھر والوں کو آگ سے بچاؤ۔',
      id: 'Peliharalah dirimu dan keluargamu dari api neraka.',
      fr: 'Préservez vos personnes et vos familles d un Feu.',
      bn: 'তোমরা নিজেদেরকে এবং তোমাদের পরিবারকে আগুন থেকে রক্ষা কর।',
      hi: 'अपने आप को और अपने परिवारों को आग से बचाओ।',
    },
    verseReference: 'At-Tahrim 66:6',
    frequency: 124,
    difficulty: 'Intermediate',
  },
  {
    id: 44,
    arabic: 'آخِرَة',
    transliteration: 'ākhirah',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Hereafter',
      ur: 'آخرت',
      id: 'Akhirat',
      fr: 'Au-delà',
      bn: 'পরকাল',
      hi: 'परलोक',
    },
    exampleVerseArabic: 'وَهُم بِالْآخِرَةِ هُمْ كَافِرُونَ',
    exampleVerseTransliteration: 'wa-hum bi-l-ākhirati hum kāfirūn',
    exampleVerseTranslations: {
      en: 'And they, in the Hereafter, are disbelievers.',
      ur: 'اور وہ آخرت کے منکر ہیں۔',
      id: 'Dan mereka terhadap akhirat adalah orang-orang yang ingkar.',
      fr: 'Et ils ne croient pas en l au-delà.',
      bn: 'এবং তারা পরকালে অবিশ্বাসী।',
      hi: 'और वे परलोक में अविश्वासी हैं।',
    },
    verseReference: 'Hud 11:19',
    frequency: 115,
    difficulty: 'Intermediate',
  },
  {
    id: 39,
    arabic: 'عِلْم',
    transliteration: 'ʿilm',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Knowledge',
      ur: 'علم',
      id: 'Ilmu, pengetahuan',
      fr: 'Science, connaissance',
      bn: 'জ্ঞান',
      hi: 'ज्ञान',
    },
    exampleVerseArabic: 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
    exampleVerseTransliteration: 'wa-qul rabbi zidnī ʿilmā',
    exampleVerseTranslations: {
      en: 'And say, "My Lord, increase me in knowledge."',
      ur: 'اور کہو، "اے میرے رب، میرے علم میں اضافہ فرما۔"',
      id: 'Dan katakanlah, "Ya Tuhanku, tambahkanlah ilmu kepadaku."',
      fr: 'Et dis: "Ô mon Seigneur, accrois mes connaissances!"',
      bn: 'এবং বলুন, "হে আমার প্রতিপালক, আমার জ্ঞান বৃদ্ধি করে দিন।"',
      hi: 'और कहो, "मेरे भगवान, मुझे ज्ञान में बढ़ाओ।"',
    },
    verseReference: 'Taha 20:114',
    frequency: 114,
    difficulty: 'Intermediate',
    root: 'ع-ل-م',
    etymology: "From the root meaning 'to know'. It refers to knowledge, learning, and awareness, a concept highly esteemed in the Quran.",
  },
  {
    id: 37,
    arabic: 'مَلَائِكَة',
    transliteration: 'malāʾikah',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Angels',
      ur: 'فرشتے',
      id: 'Malaikat',
      fr: 'Anges',
      bn: 'ফেরেশতা',
      hi: 'स्वर्गदूत',
    },
    exampleVerseArabic: 'وَإِذْ قَالَ رَبُّكَ لِلْمَلَائِكَةِ إِنِّي جَاعِلٌ فِي الْأَرْضِ خَلِيفَةً',
    exampleVerseTransliteration: 'wa-idh qāla rabbuka li-l-malāʾikati innī jāʿilun fī al-arḍi khalīfah',
    exampleVerseTranslations: {
      en: 'And [mention, O Muhammad], when your Lord said to the angels, "Indeed, I will make upon the earth a successive authority."',
      ur: 'اور جب آپ کے رب نے فرشتوں سے کہا، "میں زمین میں ایک خلیفہ بنانے والا ہوں۔"',
      id: 'Dan (ingatlah) ketika Tuhanmu berfirman kepada para malaikat, "Aku hendak menjadikan khalifah di bumi."',
      fr: 'Lorsque Ton Seigneur dit aux Anges: "Je vais établir sur la terre un vicaire".',
      bn: 'এবং যখন তোমার প্রতিপালক ফেরেশতাদের বললেন, "আমি পৃথিবীতে একজন প্রতিনিধি নিযুক্ত করতে যাচ্ছি।"',
      hi: 'और (याद करो, हे मुहम्मद), जब तुम्हारे भगवान ने स्वर्गदूतों से कहा, "निश्चित रूप से, मैं पृथ्वी पर एक उत्तराधिकारी बनाऊंगा।"',
    },
    verseReference: 'Al-Baqarah 2:30',
    frequency: 88,
    difficulty: 'Advanced',
  },
  {
    id: 20,
    arabic: 'صَلَاة',
    transliteration: 'ṣalāh',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Prayer',
      ur: 'نماز',
      id: 'Salat',
      fr: 'Prière',
      bn: 'নামাজ',
      hi: 'प्रार्थना',
    },
    exampleVerseArabic: 'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ',
    exampleVerseTransliteration: 'wa-aqīmū aṣ-ṣalāta wa-ātū az-zakāh',
    exampleVerseTranslations: {
      en: 'And establish prayer and give zakah.',
      ur: 'اور نماز قائم کرو اور زکوٰۃ دو۔',
      id: 'Dan laksanakanlah salat dan tunaikanlah zakat.',
      fr: 'Et accomplissez la Salât et acquittez la Zakât.',
      bn: 'এবং নামাজ প্রতিষ্ঠা কর ও যাকাত দাও।',
      hi: 'और नमाज़ स्थापित करो और ज़कात दो।',
    },
    verseReference: 'Al-Baqarah 2:43',
    frequency: 83,
    difficulty: 'Advanced',
  },
  {
    id: 34,
    arabic: 'إِنْسَان',
    transliteration: 'insān',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Human being',
      ur: 'انسان',
      id: 'Manusia',
      fr: 'Être humain',
      bn: 'মানুষ',
      hi: 'इंसान',
    },
    exampleVerseArabic: 'لَقَدْ خَلَقْنَا الْإِنسَانَ فِي أَحْسَنِ تَقْوِيمٍ',
    exampleVerseTransliteration: 'laqad khalaqnā al-insāna fī aḥsani taqwīm',
    exampleVerseTranslations: {
      en: 'We have certainly created man in the best of stature.',
      ur: 'یقیناً ہم نے انسان کو بہترین ساخت میں پیدا کیا ہے۔',
      id: 'Sungguh, Kami telah menciptakan manusia dalam bentuk yang sebaik-baiknya.',
      fr: 'Nous avons certes créé l homme dans la forme la plus parfaite.',
      bn: 'আমরা অবশ্যই মানুষকে সর্বোত্তম গঠনে সৃষ্টি করেছি।',
      hi: 'हमने निश्चित रूप से मनुष्य को सर्वोत्तम कद में बनाया है।',
    },
    verseReference: 'At-Tin 95:4',
    frequency: 65,
    difficulty: 'Advanced',
  },
  {
    id: 30,
    arabic: 'مَاء',
    transliteration: 'māʾ',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Water',
      ur: 'پانی',
      id: 'Air',
      fr: 'Eau',
      bn: 'পানি',
      hi: 'पानी',
    },
    exampleVerseArabic: 'وَأَنزَلْنَا مِنَ السَّمَاءِ مَاءً طَهُورًا',
    exampleVerseTransliteration: 'wa-anzalnā mina as-samāʾi māʾan ṭahūrā',
    exampleVerseTranslations: {
      en: 'And We have sent down blessed rain from the sky.',
      ur: 'اور ہم نے آسمان سے پاک کرنے والا پانی نازل کیا۔',
      id: 'Dan Kami turunkan dari langit air yang suci.',
      fr: 'Et Nous avons fait descendre du ciel une eau pure.',
      bn: 'এবং আমি আকাশ থেকে পবিত্র পানি বর্ষণ করেছি।',
      hi: 'और हमने आकाश से धन्य वर्षा भेजी है।',
    },
    verseReference: 'Al-Furqan 25:48',
    frequency: 63,
    difficulty: 'Advanced',
  },
  {
    id: 41,
    arabic: 'دُعَاء',
    transliteration: 'duʿāʾ',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Supplication, call',
      ur: 'دعا، پکار',
      id: 'Doa, panggilan',
      fr: 'Invocation, appel',
      bn: 'দুআ, আহ্বান',
      hi: 'प्रार्थना, पुकार',
    },
    exampleVerseArabic: 'وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ',
    exampleVerseTransliteration: 'wa-qāla rabbukumu idʿūnī astajib lakum',
    exampleVerseTranslations: {
      en: 'And your Lord says, "Call upon Me; I will respond to you."',
      ur: 'اور تمہارے رب نے کہا، "مجھے پکارو، میں تمہاری دعا قبول کروں گا۔"',
      id: 'Dan Tuhanmu berfirman, "Berdoalah kepada-Ku, niscaya akan Aku perkenankan bagimu."',
      fr: 'Et votre Seigneur dit: "Invoquez-Moi, Je vous répondrai."',
      bn: 'এবং তোমাদের প্রতিপালক বলেন, "তোমরা আমাকে ডাকো, আমি তোমাদের ডাকে সাড়া দেব।"',
      hi: 'और तुम्हारे भगवान कहते हैं, "मुझे पुकारो; मैं तुम्हें जवाब दूंगा।"',
    },
    verseReference: 'Ghafir 40:60',
    frequency: 44,
    difficulty: 'Advanced',
  },
  {
    id: 36,
    arabic: 'نُور',
    transliteration: 'nūr',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Light',
      ur: 'نور، روشنی',
      id: 'Cahaya',
      fr: 'Lumière',
      bn: 'আলো, নূর',
      hi: 'प्रकाश, नूर',
    },
    exampleVerseArabic: 'اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ',
    exampleVerseTransliteration: 'Allāhu nūru as-samāwāti wa-l-arḍ',
    exampleVerseTranslations: {
      en: 'Allah is the Light of the heavens and the earth.',
      ur: 'اللہ آسمانوں اور زمین کا نور ہے۔',
      id: 'Allah (pemberi) cahaya (kepada) langit dan bumi.',
      fr: 'Allah est la Lumière des cieux et de la terre.',
      bn: 'আল্লাহ আকাশমণ্ডলী ও পৃথিবীর আলো।',
      hi: 'अल्लाह आकाश और पृथ्वी का प्रकाश है।',
    },
    verseReference: 'An-Nur 24:35',
    frequency: 43,
    difficulty: 'Advanced',
  },
  {
    id: 28,
    arabic: 'زَكَاة',
    transliteration: 'zakāh',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Purifying charity',
      ur: 'زکوٰۃ',
      id: 'Zakat',
      fr: 'Aumône purificatrice',
      bn: 'যাকাত',
      hi: 'ज़कात',
    },
    exampleVerseArabic: 'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ',
    exampleVerseTransliteration: 'wa-aqīmū aṣ-ṣalāta wa-ātū az-zakāh',
    exampleVerseTranslations: {
      en: 'And establish prayer and give zakah.',
      ur: 'اور نماز قائم کرو اور زکوٰۃ دو۔',
      id: 'Dan laksanakanlah salat dan tunaikanlah zakat.',
      fr: 'Et accomplissez la Salât et acquittez la Zakât.',
      bn: 'এবং নামাজ প্রতিষ্ঠা কর ও যাকাত দাও।',
      hi: 'और नमाज़ स्थापित करो और ज़कात दो।',
    },
    verseReference: 'Al-Baqarah 2:43',
    frequency: 32,
    difficulty: 'Advanced',
  },
  {
    id: 29,
    arabic: 'صَوْم',
    transliteration: 'ṣawm',
    partOfSpeech: 'Noun',
    meanings: {
      en: 'Fasting',
      ur: 'روزہ',
      id: 'Puasa',
      fr: 'Jeûne',
      bn: 'রোজা',
      hi: 'रोज़ा',
    },
    exampleVerseArabic: 'يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ',
    exampleVerseTransliteration: 'yā ayyuhā alladhīna āmanū kutiba ʿalaykumu aṣ-ṣiyām',
    exampleVerseTranslations: {
      en: 'O you who have believed, decreed upon you is fasting.',
      ur: 'اے ایمان والو، تم پر روزہ فرض کیا گیا ہے۔',
      id: 'Wahai orang-orang yang beriman, diwajibkan atas kamu berpuasa.',
      fr: 'Ô les croyants! On vous a prescrit le jeûne.',
      bn: 'হে ঈমানদারগণ, তোমাদের উপর রোজা ফরজ করা হয়েছে।',
      hi: 'हे ईमान वालो, तुम पर रोज़ा रखना अनिवार्य किया गया है।',
    },
    verseReference: 'Al-Baqarah 2:183',
    frequency: 14,
    difficulty: 'Advanced',
  },
];